name: granizapp
description: App para control de ventas de granizados
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  fl_chart: ^0.65.0
  intl: ^0.19.0
  sqflite: ^2.3.0
  connectivity_plus: ^6.0.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  # Para desktop (opcional)
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true